name: "Rodney Bot"
description: "A bot for GitHub actions events"
author: "Jens Reimann <jreimann@redhat.com>"
branding:
  color: green
  icon: activity
inputs:
  version:
    description: "The version to use"
    required: true
    default: "v0.1.6"
  installOnly:
    description: "Set to 'true' to only install the binary"
    required: false
    default: "false"
  config:
    description: "Point to the configuration file. Defaults to 'rodbot.yaml' in the local directory."
    required: false
    default: "rodbot.yaml"
runs:
  using: composite
  steps:
    - run: "env VERSION=${{ inputs.version }} $GITHUB_ACTION_PATH/install.sh"
      shell: bash
    - run: |
        if [ "${{ inputs.installOnly }}" != "true" ]; then
          rodbot --config "${{ inputs.config }}"
        fi
      shell: bash
